export const MIN_SPIN_DURATION_SECONDS = 25;
export const MAX_SPIN_DURATION_SECONDS = 75;

export const SPIN_DURATION_RANGE_LABEL =
  `${MIN_SPIN_DURATION_SECONDS}–${MAX_SPIN_DURATION_SECONDS} seconds`;
