import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join } from "node:path";

async function run() {
  const html = await readFile(join(process.cwd(), "renderer/index.html"), "utf8");
  const css = await readFile(join(process.cwd(), "renderer/desktop-shell.css"), "utf8");
  const renderer = await readFile(join(process.cwd(), "renderer/desktop-shell.ts"), "utf8");
  const hostPreload = await readFile(join(process.cwd(), "preload/host-preload.ts"), "utf8");
  const main = await readFile(join(process.cwd(), "main/main.ts"), "utf8");
  const zoom = await readFile(join(process.cwd(), "main/zoom-settings.ts"), "utf8");
  const wheel = await readFile(join(process.cwd(), "../app/components/wheel/WheelSection.tsx"), "utf8");
  const winnerOverlay = await readFile(join(process.cwd(), "renderer/winner-overlay.ts"), "utf8");
  const winnerController = await readFile(join(process.cwd(), "main/winner/WinnerPresentationController.ts"), "utf8");
  for (const id of ["show-host", "show-facebook", "show-broadcast", "show-studio", "broadcast-panel", "broadcast-region"]) assert.match(html, new RegExp(`id="${id}"`));
  assert.match(html, /Production Studio/); assert.match(html, /OBS Status:/); assert.match(html, /id="studio-error"/);
  assert.match(html, /Program Preview/); assert.match(html, /id="program-preview-image"/); assert.match(html, /Preview status:/);
  assert.match(html, /img-src 'self' data:/, "CSP must permit in-memory OBS preview data URLs");
  assert.match(css, /Four isolated, full-window workspaces/); assert.match(css, /#host-region,#facebook-panel,#broadcast-panel,#obs-panel/);
  assert.doesNotMatch(css, /#obs-panel[^,{]*:hover|\.studio[^,{]*:hover/i, "Studio root must not have a hover background");
  assert.doesNotMatch(css, /#(?:f00|ff0000)|\b(?:red|crimson)\b/i, "desktop CSS must not contain red debug fills");
  for (const view of ["host", "facebook", "broadcast"]) assert.match(renderer, new RegExp(`panel === "${view}"`), `layout must explicitly gate ${view}`);
  assert.match(renderer, /broadcast: panel === "broadcast"/); assert.match(renderer, /host: panel === "host"/);
  assert.match(renderer, /window\.asylumDesktop\?\.obs/, "Studio must guard a missing OBS preload bridge");
  assert.match(renderer, /showStudioFailure/, "renderer errors must produce the Studio fallback");
  assert.match(renderer, /PREVIEW_INTERVAL_MS = 1_000/); assert.match(renderer, /previewInFlight/);
  assert.match(renderer, /document\.visibilityState === "visible"/); assert.match(renderer, /panel === "obs"/);
  assert.match(renderer, /beforeunload.*stopPreviewPolling/); assert.doesNotMatch(renderer, /writeFile|imageFilePath/);
  assert.match(renderer, /candidate\.onerror/); assert.match(renderer, /new Image\(\)/, "frames must decode before replacing the visible preview");
  assert.match(html, /Test Preview/); assert.match(html, /Preview bytes:/); assert.match(renderer, /testProgramPreview/);
  for (const label of ["Host Scene", "Wheel Scene", "Winner Scene", "Second Chance Scene", "Reward Chamber Scene", "Break Scene", "Ending Scene"]) assert.match(html, new RegExp(label));
  assert.match(html, /Switch to Wheel Scene when Spin starts/); assert.match(html, /Return to Host Scene after Accept Result/);
  assert.match(html, /OBS Automation Disabled/); assert.match(html, /Winner Celebration Package/);
  assert.match(renderer, /saveSceneMappings/); assert.doesNotMatch(renderer, /integration.*scene|raffle.*switchScene/i, "mapping toggles must not execute raffle automation");
  assert.match(html, /Export Studio Profile/); assert.match(html, /Import Studio Profile/); assert.match(html, /Automatic Scene Switching/);
  assert.match(renderer, /testMappedScene/); assert.doesNotMatch(renderer, /data-test-mapping[^\n]*switchScene/, "mapped tests must use the restricted mapped-scene API");
  for (const delay of ["wheel", "winner", "secondChance", "reward", "host"]) assert.match(html, new RegExp(`id="delay-${delay}"`));
  assert.match(html, /Live Show Automation/); assert.match(html, /id="automation-state"/); assert.match(html, /id="automation-log"/);
  assert.match(renderer, /getAutomationStatus/); assert.match(renderer, /onAutomationStateChanged/);
  assert.match(hostPreload, /emitAutomationEvent/); assert.doesNotMatch(hostPreload, /switchScene|obs-websocket|GetSourceScreenshot/, "host preload must expose semantic events only");
  assert.match(main, /event\.sender !== hostView\?\.webContents/); assert.match(main, /const allowed = \["SPIN"/);
  assert.match(wheel, /data\?\.intent !== "spin-wheel"[\s\S]*wheel\.type === "VALUE" \? "REWARD" : "SPIN"/); assert.doesNotMatch(wheel, /emitDesktopAutomationEvent\("SHUFFLE"/);
  assert.doesNotMatch(wheel, /onReveal\(\)[\s\S]{0,100}emitDesktopAutomationEvent/, "winner automation must not be sourced from reveal animation callbacks");
  assert.match(html, /Test Winner Overlay/); assert.match(html, /Replay Last Winner/); assert.match(html, /Hide Overlay/);
  assert.match(wheel, /data\.secondChance\?\.beforeDisplayName/); assert.doesNotMatch(wheel, /claimId.*CELEBRATE|username.*CELEBRATE/i);
  assert.match(winnerController, /handled\.has\(identity\)/); assert.match(winnerController, /audioDataUrl/); assert.doesNotMatch(renderer, /audioFile/, "shell renderer must not receive audio filesystem paths");
  assert.match(winnerOverlay, /prefers-reduced-motion/); assert.doesNotMatch(winnerOverlay, /loop\s*=/);
  assert.match(main, /ASYLUM_DESKTOP_DEVTOOLS === "1"/); assert.doesNotMatch(main, /if \(!app\.isPackaged\).*openDevTools/);
  assert.match(main, /new WebContentsView\(\{ webPreferences: \{ partition: "persist:asylum-host"[\s\S]*broadcast-preload\.js/);
  for (const id of ["broadcast-status-strip", "broadcast-fullscreen", "broadcast-clean", "broadcast-scale", "broadcast-safe-areas", "lock-active-game", "broadcast-updated"]) assert.match(html, new RegExp(`id="${id}"`));
  assert.match(css, /aspect-ratio:16 \/ 9/); assert.match(css, /body\.broadcast-clean/); assert.match(css, /body\.broadcast-fullscreen/);
  assert.match(renderer, /event\.key === "F11"/); assert.match(renderer, /input, textarea, select, \[contenteditable=true\]/); assert.match(renderer, /\{ b: "broadcast", h: "host", f: "facebook", s: "obs" \}/);
  assert.match(renderer, /confirm\("Clear the active raffle/); assert.match(renderer, /Switch anyway/); assert.match(renderer, /Broadcast state may be stale|broadcast-stale/);
  assert.match(main, /activeGame\?\.locked/); assert.match(main, /active-game:set-lock/); assert.match(main, /event\.sender !== broadcastView\?\.webContents/);
  assert.match(main, /broadcast:set-scale/); assert.match(main, /broadcast:set-safe-areas/); assert.match(main, /broadcast-preload\.js/);
  assert.match(html, /OBS Browser Source URL/); assert.match(html, /id="copy-obs-broadcast-url"/); assert.match(html, /id="regenerate-obs-broadcast-url"/); assert.match(main, /broadcast:copy-obs-url/);
  assert.match(html, /id="zoom-status"/); assert.match(main, /label: "Zoom In"/); assert.match(main, /CmdOrCtrl\+Plus/); assert.match(main, /CmdOrCtrl\+-/); assert.match(main, /CmdOrCtrl\+0/);
  for (const workspace of ["host", "facebook", "broadcast", "studio"]) assert.match(zoom, new RegExp(`${workspace}: 1`));
  for (const preset of ["0.75", "0.9", "1", "1.1", "1.25", "1.5", "1.75", "2"]) assert.ok(zoom.includes(preset), `missing zoom preset ${preset}`);
  assert.match(main, /broadcastView\?\.webContents\.setZoomFactor/); assert.match(main, /desktop:studio-zoom/); assert.match(renderer, /style\.zoom/);
  assert.match(main, /zoomStore\.save/); assert.doesNotMatch(zoom, /Prisma|PostgreSQL/);
  console.info("Studio layout and fallback tests passed");
}
void run().catch((error) => { console.error(error); process.exitCode = 1; });
